package Lucero;

public enum SyntaxKind {
    ADDITION_TOKEN,
    SUBTRACTION_TOKEN,
    MULTIPLICATION_TOKEN,
    DIVISION_TOKEN,
    NUMBER_TOKEN,
    WHITESPACE_TOKEN,
    END_TOKEN,
    BINARY_EXPRESSION,
    INVALID_TOKEN,
    NUMBER_EXPRESSION,
}
